[package]
name = "compio-signal"
version = "0.2.0"
description = "Signal handling for compio"
categories = ["asynchronous"]
keywords = ["async", "signal"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# Workspace dependencies
compio-runtime = { workspace = true, features = ["event"] }

once_cell = { workspace = true }
slab = { workspace = true }

# Windows specific dependencies
[target.'cfg(windows)'.dependencies]
compio-driver = { workspace = true }
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Console",
] }

# Unix specific dependencies
[target.'cfg(unix)'.dependencies]
os_pipe = { workspace = true }
libc = { workspace = true }

[features]
# Nightly features
lazy_cell = []
once_cell_try = []
nightly = ["lazy_cell", "once_cell_try"]
